# Generated by Django 5.1.1 on 2024-09-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('length', models.CharField(default=0, max_length=20)),
                ('width', models.CharField(default=0, max_length=20)),
                ('height', models.CharField(default=0, max_length=20)),
                ('main_foto', models.ImageField(blank=True, null=True, upload_to='main_product_images')),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('recommended_place_of_using', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('length', models.CharField(default=0, max_length=20)),
                ('width', models.CharField(default=0, max_length=20)),
                ('height', models.CharField(default=0, max_length=20)),
                ('main_foto', models.ImageField(blank=True, null=True, upload_to='main_product_images')),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images')),
                ('image_mini', models.ImageField(blank=True, null=True, upload_to='mini_product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('characteristic', models.TextField()),
                ('length', models.CharField(default=0, max_length=20)),
                ('width', models.CharField(default=0, max_length=20)),
                ('height', models.CharField(default=0, max_length=20)),
                ('main_foto', models.ImageField(blank=True, null=True, upload_to='main_product_images')),
            ],
        ),
    ]
