# Generated by Django 5.1 on 2024-10-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
