# Generated by Django 5.1 on 2024-10-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_basket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
